-- =============================================================================
-- Online Voting System - Database Schema
-- =============================================================================
-- This SQL schema defines the database structure for the Online Voting System
-- Run this script to create the required tables in MySQL
-- =============================================================================

-- Create database (if not exists)
CREATE DATABASE IF NOT EXISTS online_voting_system;
USE online_voting_system;

-- =============================================================================
-- Table: users
-- Stores registered voters and administrators
-- =============================================================================
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(80) UNIQUE NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('admin', 'voter') NOT NULL DEFAULT 'voter',
    is_verified BOOLEAN DEFAULT FALSE,
    verification_token VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_email (email),
    INDEX idx_username (username),
    INDEX idx_role (role),
    INDEX idx_is_verified (is_verified)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Table: candidates
-- Stores election candidates
-- =============================================================================
CREATE TABLE IF NOT EXISTS candidates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    party VARCHAR(150),
    description TEXT,
    image_url VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_name (name),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Table: votes
-- Stores encrypted votes
-- =============================================================================
CREATE TABLE IF NOT EXISTS votes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    voter_id INT NOT NULL,
    candidate_id INT NOT NULL,
    encrypted_vote TEXT NOT NULL,
    vote_hash VARCHAR(255) NOT NULL,
    voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (voter_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE,
    UNIQUE KEY unique_voter_vote (voter_id),
    INDEX idx_voter_id (voter_id),
    INDEX idx_candidate_id (candidate_id),
    INDEX idx_voted_at (voted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Table: election_settings
-- Stores election configuration
-- =============================================================================
CREATE TABLE IF NOT EXISTS election_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    election_name VARCHAR(100) NOT NULL DEFAULT 'General Election',
    election_description TEXT,
    start_date TIMESTAMP NULL,
    end_date TIMESTAMP NULL,
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Insert default admin user (password: Admin@123)
-- Note: In production, use a properly hashed password
-- Default admin credentials: admin / Admin@123
-- =============================================================================
-- The password hash will be generated by the application on first run

-- =============================================================================
-- Insert sample election settings
-- =============================================================================
INSERT INTO election_settings (election_name, election_description, is_active) 
VALUES ('General Election 2024', 'Annual General Election for voting', TRUE)
ON DUPLICATE KEY UPDATE election_name = election_name;

-- =============================================================================
-- Sample Candidates (for testing)
-- =============================================================================
-- These will be added through the admin panel

-- =============================================================================
-- Views for common queries
-- =============================================================================

-- View: Get voting results with candidate details
CREATE OR REPLACE VIEW voting_results AS
SELECT 
    c.id AS candidate_id,
    c.name AS candidate_name,
    c.party,
    COUNT(v.id) AS vote_count
FROM candidates c
LEFT JOIN votes v ON c.id = v.candidate_id
WHERE c.is_active = TRUE
GROUP BY c.id, c.name, c.party
ORDER BY vote_count DESC;

-- View: Get all verified voters
CREATE OR REPLACE VIEW verified_voters AS
SELECT 
    id,
    username,
    email,
    created_at
FROM users
WHERE role = 'voter' AND is_verified = TRUE;

-- =============================================================================
-- Stored Procedure: Check if voter has voted
-- =============================================================================
DELIMITER //
CREATE PROCEDURE IF NOT EXISTS has_voted(IN voter_id INT)
BEGIN
    SELECT COUNT(*) AS vote_count FROM votes WHERE voter_id = voter_id;
END //
DELIMITER ;

-- =============================================================================
-- End of Database Schema
-- =============================================================================
